# Use an official Python runtime as a parent image
FROM python:3.12.3-alpine3.19

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apk update && \
    apk add --no-cache \
    curl \
    gcc \
    musl-dev \
    python3-dev \
    libffi-dev \
    openssl-dev \
    cargo \
    postgresql-dev \
    gettext \
    && pip install --upgrade pip \
    && curl -sSL https://install.python-poetry.org | python3 -

# Copy only the requirements files to cache dependencies
COPY poetry.lock pyproject.toml /app/

# Install dependencies
RUN $HOME/.local/bin/poetry config virtualenvs.create false && \
    $HOME/.local/bin/poetry install --no-root

# Copy project
COPY . /app/

# Expose port 8000
EXPOSE 8000

# Run the application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
